spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/curso_sq15
    username: sq15
    password: secret
  jpa:
    hibernate:
      ddl-auto: update   # solo para desarrollo
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always       # si quieres scripts de inicio

server:
  port: 8080
